apply plugin: 'maven-publish'
apply plugin: 'signing'

tasks.register('androidJavadoc', Javadoc) {
    source = android.sourceSets.main.java.srcDirs
    classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
    android.libraryVariants.all { variant ->
        if (variant.name == 'release') {
            owner.classpath += variant.javaCompileProvider.get().classpath
        }
    }

    exclude '**/R.html', '**/R.*.html', '**/index.html'
    options.encoding 'utf-8'
    options {
        addStringOption 'docencoding', 'utf-8'
        addStringOption 'charset', 'utf-8'
        links 'https://docs.oracle.com/javase/7/docs/api/'
        links 'https://d.android.com/reference'
        links 'https://developer.android.com/reference/androidx/'
    }
}

tasks.register('androidJavadocJar', Jar) {
    dependsOn androidJavadoc
    archiveClassifier.set('javadoc')
    from androidJavadoc.destinationDir

    preserveFileTimestamps = false
    reproducibleFileOrder = true
}

tasks.register('javaSourcesJar', Jar) {
    archiveClassifier.set('sources')
    from android.sourceSets.main.java.srcDirs

    preserveFileTimestamps = false
    reproducibleFileOrder = true
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {

                from components.real

                // artifact androidJavadocJar
                // artifact javaSourcesJar

                groupId libs.versions.publishingGroupId.get()
                artifactId libs.versions.publishingArtifactId.get()
                version libs.versions.androidVersionName.get()

                pom {
                    name = libs.versions.pomName.get()
                    description = libs.versions.pomDescription.get()
                    url = libs.versions.pomUrl.get()

                    licenses {
                        license {
                            name = libs.versions.pomLicenceName.get()
                            url = libs.versions.pomLicenceUrl.get()
                        }
                    }

                    scm {
                        connection = libs.versions.pomScmConnection.get()
                        developerConnection = libs.versions.pomScmDevConnection.get()
                        url = libs.versions.pomScmUrl.get()
                    }

                    developers {
                        developer {
                            id = libs.versions.pomDeveloperId.get()
                            name = libs.versions.pomDeveloperName.get()
                            email = libs.versions.pomDeveloperEmail.get()
                        }
                    }
                }
            }
        }

        repositories {
            maven {
                def releasesRepoUrl = "https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/"
                def snapshotsRepoUrl = "https://s01.oss.sonatype.org/content/repositories/snapshots/"
                url = version.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl

                credentials {
                    username ossrhUsername
                    password ossrhPassword
                }
            }

            mavenLocal()
        }
    }
}

signing {
    sign publishing.publications
}