# ----------------------------------------------------------------------------------------------------------------------
[versions]
# Plugin
agp = "8.4.2"
kotlin = "1.9.0"

# Main Dependency --------------------------------
androidxCoreKtx = "1.13.1"

# Compose
activityCompose = "1.9.3"
composeBom = "2023.08.00"

# Test Dependency --------------------------------
junit = "4.13.2"
androidxJunit = "1.2.1"
androidxEspressoCore = "3.6.1"

# ----------------------------------------------------------------------------------------------------------------------
[libraries]
# Main Dependency --------------------------------
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCoreKtx" }
com-google-android-material = { group = "com.google.android.material", name = "material", version = "1.12.0" }
com-google-code-gson = { group = "com.google.code.gson", name = "gson", version = "2.10.1" }

# Test Dependency --------------------------------
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspressoCore" }
org-mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version = "3.2.0" }
org-mockito-inline = { group = "org.mockito", name = "mockito-inline", version = "5.2.0" }
org-jetbrains-kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version = "1.8.1" }

# Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

# ----------------------------------------------------------------------------------------------------------------------
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
com-android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

# ----------------------------------------------------------------------------------------------------------------------
[bundles]
# Main Bundles --------------------------------

# Test Bundles --------------------------------
org-mockito-test = [
    "org-mockito-kotlin",
    "org-mockito-inline"
]
